"""Add licence_key to user table

Revision ID: 7c214517dd0f
Revises: 550fe97dac81
Create Date: 2025-04-23 23:37:09.138986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c214517dd0f'
down_revision: Union[str, None] = '550fe97dac81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('licence_key', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('users_password_reset_token_key', 'users', type_='unique')
    op.drop_constraint('users_verification_token_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_licence_key'), 'users', ['licence_key'], unique=False)
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=True)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_licence_key'), table_name='users')
    op.create_unique_constraint('users_verification_token_key', 'users', ['verification_token'])
    op.create_unique_constraint('users_password_reset_token_key', 'users', ['password_reset_token'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'licence_key')
    # ### end Alembic commands ###
